version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mhsITB313
      POSTGRES_DB: library_management_service
    ports:
      - "5432:5432"
  mongo:
    image: mongo
    ports:
      - "27017:27017"