author-service:
  build:
    context: ./book-service
  ports:
    - "3002:3001"
  depends_on:
    - postgres
    - mongo
  environment:
    POSTGRES_HOST: postgres
    POSTGRES_PORT: 5432
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: mhsITB313
    POSTGRES_DB: library_management_service
    MONGODB_URI: mongodb://mongo:27017/library_logs
